apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.app }}
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.app }}
  template:
    metadata:
      name: {{ .Values.application.name }}
      labels:
        app: {{ .Values.application.app }}
    spec:
      containers:
        - name: {{ .Values.application.name }}
          image: {{ .Values.application.image }}:{{ .Values.application.version }}
          ports:
            - containerPort: {{ .Values.application.containerPort }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/test
              name: test
              readOnly: true
          livenessProbe:
            exec:
              command:
                - curl
                - --fail
                - http://localhost:8080/demo
            initialDelaySeconds: 45
            periodSeconds: 5
            failureThreshold: 1
      restartPolicy: Always
      volumes:
        - name: test
          configMap:
            name: mongo-config-map