apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
spec:
  selector:
    app: {{ .Values.application.app }}
  ports: {{ .Values.application.ports | toYaml | nindent 4 }}
  type: LoadBalancer
